GET  http://localhost:4004/browse/EmployeeMaster

###
POST http://localhost:4004/browse/EmployeeMaster
Content-Type: application/json

{
    "employeeName"        : "Sathis",
    "employeeAge"         : 29,
    "employeeDateOfBirth" : "1992-03-16",
    "nationality"         : "Indian",
    "employeeHireDate"    : "2021-01-01",
    "fullTime"            : true,
    "marriedStatus"       : "Married",
    "employeeExperience"  : [{
        "organizationName"   : "Infosys",
        "relevantExperience" : 5,
        "branchCode"         : "Test",
        "location"           : "Test"
    }]
}

###
GET http://localhost:4004/browse/EmployeeMaster?$expand=employeeExperience