GET  http://localhost:4004/browse/EmployeeMaster

###
POST http://localhost:4004/browse/EmployeeMaster
Content-Type: application/json

{
    "firstName"        : "Emp Code Test",
    "age"              : 29,
    "dateOfBirth"      : "1992-03-16",
    "nationality"      : "Indian",
    "employeeType"     : "P",
    "marriedStatus"    : "S",
    "gender"           : "M"
}

###
GET http://localhost:4004/browse/EmployeeMaster?$expand=employeeExperience