GET  http://localhost:4004/browse/EmployeeMaster

###
POST http://localhost:4004/browse/EmployeeMaster
Content-Type: application/json

{
    "firstName": "Sathis Kumar",
    "lastname": "M",
    "age": 31,
    "gender": "M",
    "dateOfBirth": "1992-03-16",
    "nationality": "Indian",
    "Email": "sathi@cap.com",
    "mobile": "+9198653456789",
    "employeeType": "P",
    "employeeActive": true,
    "marriedStatus": "S",
    "departmentCode": "FULLSTACK",
    "departmentName": "Full Stack Development",
    "departmentDescription": "SAP FIOIR & UI5 Development"
}

###
POST http://localhost:4004/browse/EmployeeMaster
Content-Type: application/json

{
    "firstName": "Loganatan",
    "lastname": "Chinnasamy",
    "age": 28,
    "gender": "M",
    "dateOfBirth": "1994-03-16",
    "nationality": "Indian",
    "Email": "logan@cap.com",
    "mobile": "+9198653456789",
    "employeeType": "P",
    "employeeActive": true,
    "marriedStatus": "S",
    "departmentCode": "FULLSTACK",
    "departmentName": "Full Stack Development",
    "departmentDescription": "SAP FIOIR & UI5 Development"
}

###
POST http://localhost:4004/browse/GenderVH
Content-Type: application/json

{
    "ID" : "M",
    "genderText" : "Male"
}

###
GET http://localhost:4004/browse/EmployeeMaster?$expand=employeeExperience